language: php

php:
  - 7
  - 7.1

before_script:
  - echo 'xdebug.overload_var_dump=0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer update

script:
  - mkdir -p build/logs
  - composer test

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
